name: pytorch-derecho
channels:
  - file:///glade/work/benkirk/consulting/conda-recipes/output
  - conda-forge/label/mpi-external
  - conda-forge
dependencies:
  - python=3.11
  - mpi4py =*=derecho*
  - pip
  - pytorch ==2.8.0=derecho*2000
  - torchvision =*=derecho*
  - pyyaml
  - numpy
