name: pytorch_cuda_env
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.11.*
  - numpy<1.24
  - xarray
  - pandas
  - pytorch=2.1.2
  - torchvision=0.16.2
  - pytorch-cuda=12.1
